import { cn } from '@/lib/utils'

/**
 * Generative Patagonian scene, shown where an entity has no photograph yet.
 *
 * The platform ships with no stock photography on purpose: presenting generic
 * images as El Calafate would misrepresent what a traveller is buying. Rather
 * than a grey box, this draws a landscape — deterministic from a seed, so a
 * given tour always gets the same scene across renders and deploys.
 *
 * What makes it read as a landscape rather than a chart:
 *  · ridgelines generated by midpoint displacement, not hand-placed polygons
 *  · atmospheric perspective — distant ranges lighter and lower-contrast
 *  · snow caps above a height threshold
 *  · water that mirrors the sky, with a horizon glow
 *
 * Pure computation, no client JavaScript: it renders on the server as inline
 * SVG and costs one paint, not one request.
 */

/** Deterministic PRNG (mulberry32) — same seed, same scene, every time. */
function makeRandom(seed: number) {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) >>> 0
    let t = state
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function hashSeed(seed: string): number {
  let value = 2166136261
  for (let i = 0; i < seed.length; i += 1) {
    value ^= seed.charCodeAt(i)
    value = Math.imul(value, 16777619)
  }
  return value >>> 0
}

/**
 * Midpoint displacement: repeatedly split each segment and nudge the midpoint.
 * Produces a self-similar ridge that reads as terrain, where evenly spaced
 * points read as a graph.
 */
function ridgeline(
  random: () => number,
  baseY: number,
  amplitude: number,
  roughness: number,
  steps: number,
): number[] {
  let points = [baseY + (random() - 0.5) * amplitude, baseY + (random() - 0.5) * amplitude]
  let range = amplitude

  for (let pass = 0; pass < steps; pass += 1) {
    const next: number[] = []
    for (let i = 0; i < points.length - 1; i += 1) {
      const a = points[i]!
      const b = points[i + 1]!
      next.push(a, (a + b) / 2 + (random() - 0.5) * range)
    }
    next.push(points[points.length - 1]!)
    points = next
    range *= roughness
  }

  return points
}

/**
 * Smooth ridge path, closed to the bottom of the frame.
 *
 * Uses a Catmull-Rom spline converted to cubic Béziers, which passes exactly
 * THROUGH every point. A quadratic-through-midpoints curve is smoother but
 * misses the points, which left the snow caps floating above the ridgeline
 * they were meant to sit on.
 */
function ridgePath(points: number[], width: number, height: number): string {
  const step = width / (points.length - 1)
  const at = (i: number) => points[Math.max(0, Math.min(points.length - 1, i))]!

  let d = `M 0 ${at(0).toFixed(1)}`

  for (let i = 0; i < points.length - 1; i += 1) {
    const p0 = at(i - 1)
    const p1 = at(i)
    const p2 = at(i + 1)
    const p3 = at(i + 2)

    const x1 = i * step
    const x2 = (i + 1) * step

    // Catmull-Rom → cubic Bézier control points.
    const c1x = x1 + step / 3
    const c1y = p1 + (p2 - p0) / 6
    const c2x = x2 - step / 3
    const c2y = p2 - (p3 - p1) / 6

    d += ` C ${c1x.toFixed(1)} ${c1y.toFixed(1)}, ${c2x.toFixed(1)} ${c2y.toFixed(1)}, ${x2.toFixed(1)} ${p2.toFixed(1)}`
  }

  d += ` L ${width} ${height} L 0 ${height} Z`
  return d
}

/**
 * Snow caps sitting exactly on the ridge.
 *
 * Each cap is bounded below by a line between the two neighbouring ridge
 * points, so it hugs the terrain instead of hovering over it. Only genuine
 * local peaks above the snow line are capped.
 */
function snowCaps(points: number[], width: number, snowLine: number): string {
  const step = width / (points.length - 1)
  let d = ''

  for (let i = 1; i < points.length - 1; i += 1) {
    const y = points[i]!
    const prev = points[i - 1]!
    const next = points[i + 1]!

    // Above the snow line (smaller y is higher) and a genuine local maximum.
    if (y > snowLine || y >= prev || y >= next) continue

    const x = i * step
    // How far down each flank the snow reaches, proportional to prominence.
    const prominence = Math.min(prev, next) - y
    const reach = Math.min(0.85, 0.35 + prominence / 70)

    const leftX = x - step * reach
    const leftY = y + (prev - y) * reach
    const rightX = x + step * reach
    const rightY = y + (next - y) * reach

    // Peak, down the right flank, back along the ridge, up the left flank.
    d += `M ${x.toFixed(1)} ${y.toFixed(1)} ` +
         `L ${rightX.toFixed(1)} ${rightY.toFixed(1)} ` +
         `L ${leftX.toFixed(1)} ${leftY.toFixed(1)} Z `
  }

  return d
}

/**
 * Palettes drawn from the region: glacier meltwater, lenga forest in autumn,
 * the dry steppe, and dusk over the lake.
 */
const PALETTES = [
  {
    // Glacier blue, midday
    skyTop: '#2a6c8c', skyBottom: '#bcdce9', sun: '#ffffff',
    far: '#5b8ba6', mid: '#33647f', near: '#21455a',
    water: '#2f7796', waterDeep: '#17394c', snow: '#f4fbff',
  },
  {
    // Dusk over Lago Argentino
    skyTop: '#244a5f', skyBottom: '#d8b48c', sun: '#ffd9a8',
    far: '#4e6f82', mid: '#2e4f63', near: '#1a3341',
    water: '#3a6e86', waterDeep: '#152c3a', snow: '#ffeede',
  },
  {
    // Lenga forest, autumn
    skyTop: '#3d6b74', skyBottom: '#cfe0d6', sun: '#fdf6e8',
    far: '#5f8a7b', mid: '#3a6355', near: '#21372f', // lenga-950
    water: '#417a6c', waterDeep: '#18302a', snow: '#f2fbf6',
  },
  {
    // Steppe, warm light
    skyTop: '#5d7f94', skyBottom: '#e3d6bf', sun: '#fff4dd',
    far: '#8d9a8c', mid: '#6b6f5e', near: '#3f4034',
    water: '#6d8a86', waterDeep: '#33403c', snow: '#fffaf0',
  },
  {
    // Cold, overcast — the Patagonian default
    skyTop: '#4a6272', skyBottom: '#c3d2da', sun: '#e8f1f6',
    far: '#7c93a1', mid: '#53707f', near: '#2c4250',
    water: '#5b8397', waterDeep: '#21343f', snow: '#ffffff',
  },
] as const

const W = 400
const H = 300

export function PhotoPlaceholder({
  seed,
  className,
  label,
}: {
  seed: string
  className?: string
  /** Optional caption, e.g. on a hero. */
  label?: string
}) {
  const hashed = hashSeed(seed)
  const random = makeRandom(hashed)
  const palette = PALETTES[hashed % PALETTES.length]!

  // Unique id per instance: several placeholders share a page, and duplicate
  // gradient ids would make them all paint with the first one's fill.
  const uid = `ph${(hashed % 0xffffff).toString(36)}`

  const horizon = 168 + Math.round(random() * 26)

  const far = ridgeline(random, horizon - 66, 58, 0.56, 5)
  const mid = ridgeline(random, horizon - 34, 44, 0.54, 5)
  const near = ridgeline(random, horizon - 8, 30, 0.5, 4)

  const sunX = 60 + random() * 280
  const sunY = horizon - 96 - random() * 34
  const hasSun = random() > 0.35

  return (
    <div
      className={cn('absolute inset-0 size-full overflow-hidden bg-stone-100', className)}
      // Decorative: the surrounding card or figure carries the accessible name.
      role="presentation"
      aria-hidden="true"
    >
      <svg
        viewBox={`0 0 ${W} ${H}`}
        preserveAspectRatio="xMidYMid slice"
        className="size-full"
      >
        <defs>
          <linearGradient id={`${uid}-sky`} x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={palette.skyTop} />
            <stop offset="72%" stopColor={palette.skyBottom} />
            <stop offset="100%" stopColor={palette.skyBottom} />
          </linearGradient>

          <linearGradient id={`${uid}-water`} x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={palette.water} />
            <stop offset="100%" stopColor={palette.waterDeep} />
          </linearGradient>

          {/* Haze behind each range: the core of atmospheric perspective. */}
          <linearGradient id={`${uid}-haze`} x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={palette.skyBottom} stopOpacity="0" />
            <stop offset="100%" stopColor={palette.skyBottom} stopOpacity="0.72" />
          </linearGradient>

          <radialGradient id={`${uid}-glow`}>
            <stop offset="0%" stopColor={palette.sun} stopOpacity="0.85" />
            <stop offset="100%" stopColor={palette.sun} stopOpacity="0" />
          </radialGradient>
        </defs>

        <rect width={W} height={H} fill={`url(#${uid}-sky)`} />

        {hasSun ? (
          <>
            <circle cx={sunX} cy={sunY} r="46" fill={`url(#${uid}-glow)`} />
            <circle cx={sunX} cy={sunY} r="8" fill={palette.sun} opacity="0.9" />
          </>
        ) : null}

        {/* Far range */}
        <path d={ridgePath(far, W, H)} fill={palette.far} opacity="0.55" />
        <path d={snowCaps(far, W, horizon - 74)} fill={palette.snow} opacity="0.45" />
        <rect y={horizon - 90} width={W} height="90" fill={`url(#${uid}-haze)`} opacity="0.55" />

        {/* Mid range */}
        <path d={ridgePath(mid, W, H)} fill={palette.mid} opacity="0.85" />
        <path d={snowCaps(mid, W, horizon - 44)} fill={palette.snow} opacity="0.6" />
        <rect y={horizon - 54} width={W} height="60" fill={`url(#${uid}-haze)`} opacity="0.32" />

        {/* Near range */}
        <path d={ridgePath(near, W, H)} fill={palette.near} />
        <path d={snowCaps(near, W, horizon - 18)} fill={palette.snow} opacity="0.42" />

        {/* Water */}
        <rect y={horizon} width={W} height={H - horizon} fill={`url(#${uid}-water)`} />
        {/* Horizon glow — where the sky meets the lake. */}
        <rect y={horizon} width={W} height="3" fill={palette.snow} opacity="0.3" />

        {/* Reflection of the near range, compressed and faded. */}
        <g transform={`translate(0 ${horizon * 2}) scale(1 -0.38)`} opacity="0.2">
          <path d={ridgePath(near, W, H)} fill={palette.snow} />
        </g>

        {/* Drifting ice */}
        {Array.from({ length: 3 }, (_, i) => {
          const iceX = 30 + random() * 340
          const iceY = horizon + 14 + random() * (H - horizon - 24)
          const iceW = 12 + random() * 34
          return (
            <ellipse
              key={i}
              cx={iceX}
              cy={iceY}
              rx={iceW}
              ry={iceW * 0.16}
              fill={palette.snow}
              opacity={0.28 + random() * 0.3}
            />
          )
        })}
      </svg>

      {label ? (
        <div className="absolute inset-x-0 bottom-0 p-4">
          <span className="text-[0.6875rem] font-medium uppercase tracking-wider text-white/75">
            {label}
          </span>
        </div>
      ) : null}
    </div>
  )
}
