#!/usr/bin/env bash
#
# Refresh the Cloudflare IP ranges used for real-client-IP restoration.
#
#   sudo /var/www/vamoscalafate/deploy/scripts/update-cloudflare-ips.sh
#
# Cloudflare adds ranges occasionally. A stale list means requests from a new
# range are not recognised, so nginx records the Cloudflare address instead of
# the visitor's — silently lumping traffic into one rate-limit bucket.
#
# Safe to run from cron monthly:
#   0 4 1 * * /var/www/vamoscalafate/deploy/scripts/update-cloudflare-ips.sh --quiet

set -Eeuo pipefail

TARGET="${TARGET:-/etc/nginx/snippets/cloudflare-real-ip.conf}"
QUIET="${1:-}"

say() { [ "$QUIET" = "--quiet" ] || echo "$1"; }

V4="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)" || {
  echo "Could not fetch Cloudflare IPv4 ranges — leaving the existing file alone." >&2
  exit 1
}
V6="$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)" || {
  echo "Could not fetch Cloudflare IPv6 ranges — leaving the existing file alone." >&2
  exit 1
}

# Refuse to write a file that looks wrong. An empty or truncated response
# would otherwise produce a config that trusts nothing (or worse).
[ "$(echo "$V4" | wc -l)" -ge 10 ] || { echo "IPv4 list looks truncated; aborting." >&2; exit 1; }
[ "$(echo "$V6" | wc -l)" -ge 5 ]  || { echo "IPv6 list looks truncated; aborting." >&2; exit 1; }

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%FT%TZ)"
  echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6"
  echo "# Do not edit by hand — re-run the script instead."
  echo
  echo "# --- BEGIN CLOUDFLARE IPv4 ---"
  echo "$V4" | while read -r cidr; do [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"; done
  echo "# --- END CLOUDFLARE IPv4 ---"
  echo
  echo "# --- BEGIN CLOUDFLARE IPv6 ---"
  echo "$V6" | while read -r cidr; do [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"; done
  echo "# --- END CLOUDFLARE IPv6 ---"
  echo
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

if [ -f "$TARGET" ] && cmp -s "$TMP" "$TARGET"; then
  say "Cloudflare ranges unchanged."
  exit 0
fi

install -m 644 "$TMP" "$TARGET"
say "Updated $TARGET"

# Only reload if the whole configuration still validates.
if nginx -t 2>/dev/null; then
  systemctl reload nginx
  say "Nginx reloaded."
else
  echo "nginx -t FAILED after the update — not reloading. Check $TARGET." >&2
  exit 1
fi
