import Image from 'next/image'
import Link from 'next/link'
import { cn } from '@/lib/utils'

/**
 * Brand logo, from the artwork in public/logo.png.
 *
 * The image already contains the name, so there is no separate wordmark.
 * Two renditions are generated by scripts/generate-brand-assets.mjs:
 *  · logo.png       — navy and blue lettering, for light surfaces;
 *  · logo-light.png — white and sky-blue lettering, for photographs, the
 *                     dark footer and dark mode, where navy would vanish.
 *
 * `tone` names the BACKGROUND: "dark" = light page surface (default, which
 * also follows the theme), "light" = on a photo or dark band.
 */
const WIDTH = 646
const HEIGHT = 192

export function Logo({
  tone = 'dark',
  size = 'md',
  className,
  priority = false,
}: {
  tone?: 'dark' | 'light'
  size?: 'sm' | 'md' | 'lg'
  className?: string
  priority?: boolean
}) {
  // Rendered height; width follows the artwork's 3.36:1 ratio.
  const height = { sm: 'h-8', md: 'h-10 sm:h-11', lg: 'h-12 sm:h-14' }[size]
  const common = { width: WIDTH, height: HEIGHT, unoptimized: true, priority }

  return (
    <Link
      href="/"
      aria-label="Vamos Calafate - inicio"
      className={cn('inline-flex shrink-0 items-center', className)}
    >
      {tone === 'light' ? (
        <Image src="/brand/logo-light.png" alt="" {...common} className={cn(height, 'w-auto')} />
      ) : (
        <>
          <Image src="/brand/logo.png" alt="" {...common} className={cn(height, 'w-auto dark:hidden')} />
          <Image src="/brand/logo-light.png" alt="" {...common} className={cn(height, 'hidden w-auto dark:block')} />
        </>
      )}
    </Link>
  )
}
